# -*- coding: utf-8 -*-
"""names

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mmykU7bvtuh2FB91Xjt1pruhkfgLjpx
"""

#Asks the user to input a name
name = input("Enter the name of the pupil: ")
i = 1 #Algoritm starts counting the frst name from number 1

#When the input word isn't == to "Stop", the while loop repeats asking the user to input names
while name != "Stop" :
    name = input("Enter the name of the pupil: ")
    i += 1 #keeps track of the number of the names by adding 1 for every name

#Prints the amount of names input minus the word "Stop", therefore i-1 is used
print("The amount of students in this class is:", i-1)